# Windows builds.
name: Windows
runs:
    using: composite
    steps:
    - name: Install CUDA
      shell: powershell
      run: |
           Invoke-WebRequest https://raw.githubusercontent.com/KonduitAI/cuda-install/master/.github/actions/install-cuda-windows/install_cuda_windows.ps1 -OutFile install_cuda_windows.ps1 | Out-Null
           .\install_cuda_windows.ps1
