# Compile project on Ubuntu
name: Run Cuda install Ubuntu
runs:
    using: composite
    steps:
    - name: Install CUDA
      run: |
        wget https://raw.githubusercontent.com/KonduitAI/cuda-install/master/.github/actions/install-cuda-ubuntu/install_cuda_ubuntu.sh
        chmod +x ./install_cuda_ubuntu.sh
        source ./github/actions/install-cuda-ubuntu/install_cuda_ubuntu.sh
        if [[ $? -eq 0 ]]; then
          # Set paths for subsequent steps, using ${CUDA_PATH}
          echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
          echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        fi
      shell: bash

    # Specify the correct host compilers
    - name: Install/Select gcc and g++
      shell: bash
      run: |
        sudo apt-get install -y gcc-${{ env.GCC }} g++-${{ env.GCC }}
        echo "CC=/usr/bin/gcc-${{ env.GCC }}" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-${{ env.GCC }}" >> $GITHUB_ENV
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ env.GCC }}" >> $GITHUB_ENV

